# Service to dynamically add new waypoint

# @warning w and Va_d always have to be valid; the chi_d is optional.
float32[3] w		# Waypoint in local NED (m) or LLA
bool lla            # Set this flag true if the waypoint is given in LLA and not NED
float32 chi_d		# Desired course at this waypoint (rad)
bool use_chi		# Desired course valid (dubin or fillet paths)
float32 va_d		# Desired airspeed (m/s)
bool set_current	# Sets this waypoint to be executed now! Starts a new list
bool publish_now    # Immediately publishes the waypoint after adding
---
bool success
string message